name: FSeaTech 自动签到＋邮件通知

on:
  schedule:
    - cron: '0 0 * * *'    # 零点
  workflow_dispatch:        

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 更新 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'  # 👿20-24
      
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装requests
        run: pip install requests

      - name: 执行签到并发邮件
        env:
          WS_COOKIE: ${{ secrets.WS_COOKIE }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          TO_MAIL: ${{ secrets.TO_MAIL }}
        run: python checkin.py
